/* SPDX-License-Identifier: AGPL-3.0-or-later */
/* Offline UI checks. Install Playwright outside the app or supply NODE_PATH. */
"use strict";
const { chromium } = require("playwright");
const { pathToFileURL } = require("node:url");
const path = require("node:path");
const assert = require("node:assert/strict");
(async () => {
    const preview = process.argv[2];
    if (!preview)
        throw new Error("Pass path to HTML generated by tools/preview.php");
    const browser = await chromium.launch({
        headless: true,
        executablePath: process.env.VF_BROWSER_PATH || undefined,
    });
    let count = 0;
    const check = (valid, label) => {
        assert.ok(valid, label);
        count++;
        console.log("PASS " + label);
    };
    try {
        const page = await browser.newPage({
            viewport: { width: 1280, height: 1000 },
        });
        const errors = [];
        page.on("pageerror", (error) => errors.push(error.message));
        await page.goto(pathToFileURL(path.resolve(preview)).href);
        check(
            (await page.locator("#vf-admin h2").textContent()) ===
                "Anmeldung & Vereinsrollen",
            "admin UI loads",
        );
        check(
            (await page.locator("#vf-links .vf-row").count()) === 0,
            "no automatic account mapping",
        );
        check(await page.locator('input[name="rememberMeDefault"]').isChecked(), 'remember preselection admin option enabled by default');
        await page.locator('input[name="rememberMeDefault"]').uncheck();
        await page.locator("#vf-add-link").click();
        await page
            .getByRole("textbox", { name: "Vereinsflieger-ID", exact: true })
            .fill("42");
        await page
            .getByRole("textbox", { name: "Nextcloud-Konto-ID", exact: true })
            .fill("existing-test-account");
        check(
            (await page.locator("#vf-links .vf-row").count()) === 1,
            "add account row",
        );
        await page.locator("#vf-add-role").click();
        await page
            .getByRole("combobox", {
                name: "Vereinsflieger-Rolle",
                exact: true,
            })
            .selectOption("Technisches Personal");
        await page
            .getByRole("combobox", { name: "Nextcloud-Gruppe", exact: true })
            .selectOption("Technik");
        check(
            (await page
                .getByRole("combobox", {
                    name: "Nextcloud-Gruppe",
                    exact: true,
                })
                .locator('option[value="admin"]')
                .count()) === 0,
            "admin group absent from UI choices",
        );
        check(
            (await page
                .getByRole("combobox", {
                    name: "Vereinsflieger-Rolle",
                    exact: true,
                })
                .locator("option")
                .count()) === 3 &&
                (await page.locator("#vf-role-map input").count()) === 0,
            "role matching uses only stored exact names without free text",
        );
        await page.locator('input[name="cid"]').fill("123");
        check(
            !(await page.locator('input[name="defaultLogin"]').isChecked()) &&
                !(await page
                    .locator('input[name="createAccounts"]')
                    .isChecked()),
            "default redirect and account creation initially disabled",
        );
        check(
            (await page
                .locator('input[name="showLocalLoginLink"]')
                .isChecked()) &&
                !(await page
                    .locator('input[name="linkExistingByEmail"]')
                    .isChecked()),
            "local link visible and email migration disabled by default",
        );
        await page.locator('input[name="showLocalLoginLink"]').uncheck();
        await page.locator('input[name="linkExistingByEmail"]').check();
        check(
            (await page
                .locator('input[name="loginFailureLimit"]')
                .inputValue()) === "3" &&
                (await page
                    .locator('input[name="loginPauseMinutes"]')
                    .inputValue()) === "15" &&
                (await page
                    .locator('input[name="hourlyApiBudget"]')
                    .inputValue()) === "0",
            "protection fields retain old defaults with hourly cap off",
        );
        await page.locator('input[name="loginFailureLimit"]').fill("4");
        await page.locator('input[name="loginPauseMinutes"]').fill("10");
        await page.locator('input[name="hourlyApiBudget"]').fill("100");
        await page
            .locator('select[name="excludedAccounts"]')
            .selectOption(["admin", "alice"]);
        await page.locator('input[name="defaultLogin"]').check();
        await page.locator('input[name="createAccounts"]').check();
        await page.evaluate(() => {
            window.fetch = async (url, options) => {
                window.__vfRequests.push({
                    url,
                    body: JSON.parse(options.body),
                });
                return {
                    ok: false,
                    json: async () => ({
                        message: "Offline validation capture",
                    }),
                };
            };
        });
        await page
            .getByRole("button", {
                name: "Einstellungen speichern",
                exact: true,
            })
            .click();
        await page.waitForFunction(() => window.__vfRequests.length === 1);
        check(
            await page.evaluate(() => {
                const s = window.__vfRequests[0].body.settings;
                return (
                    s.roleMap[0].role === "Technisches Personal" &&
                    s.roleMap[0].group === "Technik" &&
                    s.dailyApiBudget === "400"
                );
            }),
            "save sends exact selected role group and budget",
        );
        check(
            await page.evaluate(() => {
                const s = window.__vfRequests[0].body.settings;
                return (
                    s.defaultLogin === true &&
                    s.createAccounts === true &&
                    JSON.stringify(s.excludedAccounts) === '["admin","alice"]'
                );
            }),
            "save preserves multiple local-only accounts and login options",
        );
        check(
            await page.evaluate(() => {
                const s = window.__vfRequests[0].body.settings;
                return (
                    s.showLocalLoginLink === false &&
                    s.linkExistingByEmail === true && s.rememberMeDefault === false
                );
            }),
            "save sends explicit local-link and email-migration choices",
        );
        check(
            await page.evaluate(() => {
                const s = window.__vfRequests[0].body.settings;
                return (
                    s.loginFailureLimit === "4" &&
                    s.loginPauseMinutes === "10" &&
                    s.hourlyApiBudget === "100" &&
                    s.loginIpAttemptLimit === "30" &&
                    s.providerPauseMinutes === "15"
                );
            }),
            "save sends configured protection limits",
        );
        check(
            (await page.locator('a[href="/login?direct=1"]').count()) === 1,
            "local escape URL visible in admin UI",
        );
        await page.evaluate(() => {
            window.__vfRequests = [];
            window.fetch = async (url, options) => {
                window.__vfRequests.push({
                    url,
                    body: JSON.parse(options.body),
                });
                return {
                    ok: true,
                    json: async () => ({
                        message: "Offline-Vorschau: keine API aufgerufen.",
                    }),
                };
            };
        });
        check(
            !(await page.locator('input[name="enabled"]').isChecked()) &&
                !(await page.locator('input[name="syncRoles"]').isChecked()),
            "login and role sync start disabled",
        );
        check(
            (await page.locator(".vf-usage strong").textContent()).includes(
                "28 / 400",
            ),
            "own API usage and budget visible",
        );
        check(
            (await page
                .locator('input[name="dailyApiBudget"]')
                .inputValue()) === "400",
            "budget defaults to 400",
        );
        await page.locator("#vf-check").click();
        await page.waitForFunction(() =>
            document
                .getElementById("vf-message")
                .textContent.includes("Offline-Vorschau:"),
        );
        check(
            await page.evaluate(
                () => window.__vfRequests[0].url === "/demo/check",
            ),
            "configuration check uses local route",
        );
        check(
            (await page.locator("#vf-check-result").isVisible()) &&
                (
                    await page.locator("#vf-check-result").textContent()
                ).startsWith("OK:") &&
                (await page
                    .locator("#vf-check-result")
                    .getAttribute("data-state")) === "success",
            "local check success is visible beside button",
        );
        await page.evaluate(() => {
            window.fetch = async () => ({
                ok: false,
                json: async () => ({ message: "Zielgruppe Technik fehlt." }),
            });
        });
        await page.locator("#vf-check").click();
        await page.waitForFunction(
            () =>
                document.getElementById("vf-check-result").dataset.state ===
                "error",
        );
        check(
            (await page.locator("#vf-check-result").textContent()).includes(
                "Fehler: Zielgruppe Technik fehlt.",
            ),
            "local check shows useful error beside button",
        );
        await page.evaluate(() => {
            window.fetch = async () => {
                throw new Error("Netzwerkfehler");
            };
        });
        await page.locator("#vf-check").click();
        await page.waitForFunction(() =>
            document
                .getElementById("vf-check-result")
                .textContent.includes("Netzwerkfehler"),
        );
        check(
            (await page.locator("#vf-check-result").isVisible()) &&
                !(await page.locator("#vf-check").isDisabled()),
            "failed transport retains visible result and allows retry",
        );
        await page.locator('input[name="cid"]').fill("124");
        check(
            (await page.locator("#vf-check-result").textContent()).includes(
                "Änderungen zuerst speichern",
            ),
            "edited form does not retain stale OK state",
        );
        await page.locator("#vf-role-map button").click();
        check(
            (await page.locator("#vf-role-map .vf-row").count()) === 0,
            "remove role row",
        );
        await page.locator("#vf-links button").click();
        check(
            (await page.locator("#vf-links .vf-row").count()) === 0,
            "remove account row",
        );
        await page.screenshot({
            path: path.resolve(preview).replace(/\.html$/i, ".png"),
            fullPage: true,
        });
        await page.setViewportSize({ width: 390, height: 844 });
        await page.locator("#vf-add-link").click();
        await page.locator("#vf-add-role").click();
        check(
            await page.evaluate(
                () => document.documentElement.scrollWidth <= window.innerWidth,
            ),
            "mobile layout has no horizontal overflow",
        );
        await page.screenshot({
            path: path.resolve(preview).replace(/\.html$/i, "-mobil.png"),
            fullPage: true,
        });
        check(errors.length === 0, "no browser JavaScript errors");
        const emptyPage = await browser.newPage();
        await emptyPage.addInitScript(() => {
            document.addEventListener(
                "DOMContentLoaded",
                () => {
                    const root = document.getElementById("vf-admin");
                    const state = JSON.parse(root.dataset.state);
                    state.settings.knownRoles = [];
                    root.dataset.state = JSON.stringify(state);
                },
                { once: true },
            );
        });
        await emptyPage.goto(pathToFileURL(path.resolve(preview)).href);
        check(
            await emptyPage.locator("#vf-add-role").isDisabled(),
            "no role can be added before roles arrive",
        );
        await emptyPage.locator("#vf-check").click();
        await emptyPage.waitForFunction(() => window.__vfRequests.length === 1);
        check(
            await emptyPage.locator("#vf-add-role").isDisabled(),
            "local check does not enable empty role catalog",
        );
        await emptyPage.close();
        const missingPage = await browser.newPage();
        await missingPage.addInitScript(() => {
            document.addEventListener(
                "DOMContentLoaded",
                () => {
                    const root = document.getElementById("vf-admin");
                    const state = JSON.parse(root.dataset.state);
                    state.missingGroups = ["Deleted group"];
                    state.settings.roleMap = [
                        { role: "Mitglied", group: "Deleted group" },
                    ];
                    root.dataset.state = JSON.stringify(state);
                },
                { once: true },
            );
        });
        await missingPage.goto(pathToFileURL(path.resolve(preview)).href);
        check(
            (
                await missingPage
                    .locator("#vf-role-map option:checked")
                    .last()
                    .textContent()
            ).includes("Zielgruppe fehlt") &&
                (await missingPage
                    .locator("#vf-role-map .vf-mapping-warning")
                    .isVisible()),
            "missing group marked directly in mapping row",
        );
        await missingPage
            .getByRole("combobox", { name: "Nextcloud-Gruppe", exact: true })
            .selectOption("Mitglieder");
        check(
            !(await missingPage
                .locator("#vf-role-map .vf-mapping-warning")
                .isVisible()),
            "selecting valid group clears row warning",
        );
        await missingPage.close();
        const pausePage = await browser.newPage({ viewport: { width: 390, height: 844 } });
        await pausePage.clock.install();
        await pausePage.addInitScript(() => {
            document.addEventListener("DOMContentLoaded", () => {
                const root = document.getElementById("vf-admin");
                const state = JSON.parse(root.dataset.state);
                state.pauses = [{ id: "a".repeat(64), username: '<img src=x onerror="window.__unsafe=true">', ip: "2001:db8::1", kind: "failures", seconds: 2 }];
                root.dataset.state = JSON.stringify(state);
                let removed = false;
                window.fetch = async (url, options) => {
                    const body = JSON.parse(options.body);
                    if (url === state.listUrl) return { ok: true, json: async () => ({ items: body.kind === "pauses" && !removed ? state.pauses : [], page: body.page, hasMore: false }) };
                    window.__vfRequests.push({ url, body });
                    removed = true;
                    return { ok: true, json: async () => ({ message: "Pause removed" }) };
                };
            }, { once: true });
        });
        await pausePage.goto(pathToFileURL(path.resolve(preview)).href);
        check((await pausePage.locator("#vf-pauses img").count()) === 0 && !(await pausePage.evaluate(() => window.__unsafe)), "pause login names render as text without HTML execution");
        check((await pausePage.locator("[data-pause-until]").textContent()).includes("00:02"), "admin pause displays remaining time");
        check(await pausePage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "long pause label and IPv6 fit mobile width");
        await pausePage.clock.runFor(3000);
        check((await pausePage.locator("[data-pause-until]").textContent()).includes("Abgelaufen"), "admin pause countdown expires without provider requests");
        await pausePage.locator('input[name="cid"]').fill("321");
        await pausePage.locator("#vf-pauses .vf-pause-row button").click();
        await pausePage.waitForFunction(() => window.__vfRequests.length === 1);
        const released = await pausePage.evaluate(() => window.__vfRequests[0]);
        check(released.url === "/demo/unpause" && released.body.identifier === "a".repeat(64), "pause removal posts only selected identifier to admin route");
        check((await pausePage.locator("#vf-pauses .vf-pause-row button").count()) === 0 && (await pausePage.locator('input[name="cid"]').inputValue()) === "321", "pause removal refreshes list and preserves unsaved settings");
        await pausePage.close();
        const loginPause = await browser.newPage();
        await loginPause.clock.install();
        await loginPause.setContent('<p data-pause-seconds="2" data-pause-message="Paused %s" data-pause-expired="Ready"></p>');
        await loginPause.addScriptTag({ path: path.resolve(__dirname, "../vereinsflieger_login/js/login.js") });
        check((await loginPause.locator("p").textContent()) === "Paused 00:02", "login pause initializes readable countdown");
        await loginPause.clock.runFor(3000);
        check((await loginPause.locator("p").textContent()) === "Ready", "login pause announces expiry without submitting form");
        await loginPause.close();
        const rolePage = await browser.newPage();
        await rolePage.addInitScript(() => {
            document.addEventListener("DOMContentLoaded", () => {
                const root = document.getElementById("vf-admin");
                const state = JSON.parse(root.dataset.state);
                state.settings.knownRoles = ['Schatzmeister/Kassenwart', 'Prüfer & Vorstand', '<img src=x onerror="window.__roleUnsafe=true">'];
                state.settings.roleMap = [{ role: 'Schatzmeister/Kassenwart', group: 'Mitglieder' }];
                root.dataset.state = JSON.stringify(state);
            }, { once: true });
        });
        await rolePage.goto(pathToFileURL(path.resolve(preview)).href);
        const roleSelect = rolePage.locator('#vf-role-map select').first();
        check(await roleSelect.inputValue() === 'Schatzmeister/Kassenwart' && await roleSelect.locator('option:checked').textContent() === 'Schatzmeister/Kassenwart', 'decoded role name remains the selected mapping value');
        check((await roleSelect.locator('option').allTextContents()).includes('Prüfer & Vorstand'), 'Unicode and ampersands in custom role names displayed correctly');
        check(await rolePage.locator('#vf-role-map img').count() === 0 && !(await rolePage.evaluate(() => window.__roleUnsafe)), 'decoded role markup displayed as text without execution');
        await rolePage.close();
        console.log(
            `${count} offline browser checks passed. No Nextcloud or VF runtime used.`,
        );
    } finally {
        await browser.close();
    }
})().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
});
